### ISSUE TITLE
Debian/Ubuntu package

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#1]
<a href="https://github.com/aronasorman"><img src="https://avatars.githubusercontent.com/u/191955?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aronasorman](https://github.com/aronasorman)**
_Thursday Dec 04, 2014 at 02:13 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/2756_

----

So, we want to move away from git-based installations for Unix systems, and use the native installation methods.

This issue is for a .deb package. The ideal is to have a script that receives a directory argument and outputs a .deb file which is valid according to Debian's packaging standards (meaning it has a license file and all necessary metadata).

Note: this should be in a separate repository, but I'm just putting it here so we can all monitor it.

**Comment by aronasorman** [comment]
Any updates here @benjaoming?

**Comment by benjaoming** [comment]
@EdDixon 
Sorry about taking so long to respond to the last comment -- it's because I agree and totally feel the same way :)

I'm solving #2 firstly, because AFAIK we've agreed to implement a common CLI before we start building UIs etc.

**Comment by benjaoming** [comment]
#2 is now -> learningequality/ka-lite#2757

**Comment by benjaoming** [comment]
Design decision:

Installing something on a linux system, means installing it in various system paths. Usually `/usr/share` for platform independent stuff, `/usr/lib` for libraries, `/usr/bin` for binaries or executables, and , `/var/` for various program data.

Now, in kalite's case we wanna keep an existing tightly integrated structure for now. So I'm going with this layout:
- `/opt/kalite` for everything, except it will contain symbolic links to actual locations of stuff!! This will also be added to the python path, as `settings` and `local_settings` will live here.
- `/opt/kalite/manage.py` for the kalite manage command, I have no idea where to actually place this, as it's not currently part of a real python package, we should have something like `kalite_project.manage`.. but nevermind, this will work.

Everything that should be served goes here:
- `/var/kalite/srv/media/` for everything in the MEDIA_ROOT.
- `/var/kalite/srv/static/` for everything in the STATIC_ROOT.
- `/var/kalite/database/` for the database

Here's the main executable:
- `/usr/bin/kalite`

And then actually the python stuff should probably be installed in:
-  `/usr/lib/pythonX.X/dist-packages/`

Why do this now? Because if we don't do it, any upgrades down the road will have to look for files in deprecated paths which is gonna be annoying.. especially content and database relocation is problematic.

**Comment by yohanboniface** [comment]
One question: will we have the way to customize database path?

Context: we are integrating KA-Lite in the [Ideasbox](https://github.com/ideas-box/ideasbox.lan) server; we also have a Django application that offers a blog, a library management tool, etc. and a server management tool (restart server, stop/restart services, manage network, etc.), which also gives the possibility to backup and restore the sensible data of the server (for security, or if we want to reinstall for any reason), see https://github.com/ideas-box/ideasbox.lan/pull/69 ; as you can see backup and restore is just zipping/unzipping a certain folder where we put all the data we want to backup (for example our database, or any user content).
The plan is/was to integrate the KA-Lite database in this folder (but not the videos files), so that user profiles are backuped in the same time.

**Comment by benjaoming** [comment]
@yohanboniface thanks for taking time to share your use case. It sounds like your scenario could be solved using either just symlinks or possibly hardlinks if it's about the database file being present at a location that gets backed up. Would this be possible? Otherwise, I'm sure that a setting can be implemented, too...in fact, I would say that all settings should be reachable through environment vars... but I don't think I can come through with this for 0.13 :)

We have just discussed the issue of backup and restore of SQlite files in regards to consistency of data, exclusive access.. I don't know what the outcome was, but I think it wasn't an issue... still, keep an eye out :)

**Comment by yohanboniface** [comment]
An environment var would be perfect :)

How would you operate with a symlink? That would work for backup, but I don't see how this would work for restore. Anyway I will dig in this direction. :)

**Comment by benjaoming** [comment]
@yohanboniface Let's assume this (not sure if it matches your use case)

Database of kalite installed in: `/var/kalite/database/kalite.db`
You are backing up this location: `/home/ideasbox/backup/`

Then, what you do is:

    cd /home/ideasbox/backup/
    ln /var/kalite/database/kalite.db kalite.db

Now you have setup a hardlink so that the sqlite database file of ideasbox is the same file as the one kalite runs with. Now you just need to setup permissions so your backup user has reading rights.

**Comment by yohanboniface** [comment]
What is the status of the Debian package? it seems that the git based install is still the official one: https://learningequality.org/ka-lite/user-guides/latest or am I missing something?

**Comment by aronasorman** [comment]
@yohanboniface yup, still the official one. We pushed the installers to 0.14.

**Comment by benjaoming** [comment]
I'm working on it again now, at first I'm just doing a small test package of my own, trying to solve challenges that we've made because of bundled python packages and data that lives outside of the kalite package.

Anyways, here's where to go... nothing works yet... but you can read thoughts in the README...

https://github.com/benjaoming/installers/tree/debian-initial/debian

**Comment by jamalex** [comment]
> /opt/kalite for everything, except it will contain symbolic links to actual locations of stuff!!

This sounds like it would make the internal update process very difficult/brittle, since we'd be unpacking stuff on top of the symbolic links? Is there a practical advantage to having stuff spread around? If so, perhaps the symbolic links can go the other direction?

I definitely agree that the following things would do well to be in other folders, though:

- database
- content

> One question: will we have the way to customize database path?

This can be configured currently in local_settings.py, with `DATABASE_PATH = '...'`

**Comment by yohanboniface** [comment]
> bundled python packages

Why not fixing that in the same time?

**Comment by benjaoming** [comment]
> > bundled python packages
>
> Why not fixing that in the same time?

I'm trying to do the installer without changing any of the internals... that thing in particular is a big task because people changed code in the bundled software.

**Comment by benjaoming** [comment]
@jamalex 

> This sounds like it would make the internal update process very difficult/brittle, since we'd be unpacking stuff on top of the symbolic links?

That's really just an old comment, just disregard it :) I was analyzing the problem without taking Python packaging conventions into account. For instance, we should be finding files like this:

    resource_filename(Requirement.parse("ka-lite"), "python-packages")

Well, that's the goal at least.. not saying that it will be possible first shot.

> Is there a practical advantage to having stuff spread around?

I'd prefer to find the best possible way to distribute and package things according to how a python package should look... with the one exception that I won't change anything in ka-lite itself for now.

So whether it'll be spread around or not, I don't know... but I'll treat everything as package data and non-package data and let setuptools decide where it goes.

`python setup.py install --install-data=/path/to/data` is one option [that's available](http://structure.usc.edu/python/inst/custom-install.html) from distutils, not sure if it works properly (using setuptools, which should supersede distutils) or if it'll solve problems.

> If so, perhaps the symbolic links can go the other direction?

(talking about next steps)

I'm not sure if the symbolic links will take things in the right direction or if there's better alternatives.. actually I think the whole "legacy" symlink idea could be dangerous if it just leaves lots of dangling references that need to be cleaned up anyways.. or gathers more of that... we don't even have any legacy in this regard, we just have our codebase that we need to clean up :)

Rather than assuming static locations, the application should be able to find files by looking at some configured paths. I know this is a huge challenge because of the way that it's currently looking for data in the "ka-lite" root folder. Some of this will be avoided by setting DATABASES, MEDIA_ROOT, and STATIC_ROOT.

(talking about now)

So for now, I'm really looking for a useful transition.

I've found a huge shortcut by using stdeb which is very well-maintained, so I'm gonna go with that and see where it takes me. For now, it's quite promising because it means to use setuptools as with any other python package.

Regarding automatic installations and upgrades, I suggest we have a look at how we can build that on top of a "perfect" PyPi=>deb package. Having stdeb's py2dsc tool create a functional deb package seamlessly will be a huge indicator of a successful design.

**Comment by benjaoming** [comment]
Here is the short version of what has happened and why we can now finally close this Issue: A .deb is in place!

You can find binary packages for all architectures or directly add the new PPA to subscribe to the latest builds here:

https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite

There will be a proper announcement later on, but for those who followed the issue here, feel welcome to test it out.

**Comment by yohanboniface** [comment]
Excellent news! Congrats :)
