### ISSUE TITLE
Sign the windows installer on every release

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#10]
... or else we get this error: ![](https://s3.amazonaws.com/uploads.hipchat.com/86198/1302220/ttvpSZHxQvUvyVb/installer-warning.png)

**Comment by ruimalheiro** [comment]
@jamalex , @aronasorman , @cpauya , @benjaoming 

Following the chat I had with @aronasorman , I think we should purchase/acquire a certificate (*.pfx) to sign both the GUI and the Installer before any release.

This will protect us from "malicious" distributions. This is actually a big risk because everyone can change and build KA Lite installer with malicious code inside :)

So, we can automate the signing mechanism but we only share the certificate with trusted builders.

For the requirements, check this:
http://certhelp.ksoftware.net/support/solutions/articles/35844-what-are-the-requirements-to-obtain-a-code-signing-certificate-

What you guys think about this?

**Comment by benjaoming** [comment]
By someone running Windows for purposes of distributing open source contents, the damage has already happened, so I wouldn't find it appealing to fight MS' new certificate signing software monopoly, it's just a shame, but that's life in the MS world :)

For the warning itself... there is a sort of irresponsible behaviour in promoting a practice where you tell people to ignore security warnings, so in that sense it would seem like a good idea to play by the rules and get the certificate.

**Comment by aronasorman** [comment]
Already so so on the latest build.
