### ISSUE TITLE
Software Center issues

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#146]
Several issues pertaining Software Center installations...

 * [x] @radinamatic doesn't see the below screen at all because of an Ubuntu bug
 * [x] Add documentation about Software Center bug because it can lockup the UI
 * [x] The `$SUDO_USER` doesn't seem to be reflected when running debconf through Software Center.
 * [x] Username was only prompted when selecting the system service init.d script

![screenshot from 2015-08-27 00 47 58](https://cloud.githubusercontent.com/assets/374612/9508414/6a508082-4c55-11e5-9a64-e495c3b71d74.png)

**Comment by benjaoming** [comment]
http://askubuntu.com/questions/485036/installing-a-package-that-asks-debconf-questions-doesnt-work-with-the-software

**Comment by benjaoming** [comment]
Thread: libgtk2-perl missing from new install 

http://ubuntuforums.org/showthread.php?t=2236891

**Comment by benjaoming** [comment]
Launchpad bug:

https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/1389582

**Comment by radinamatic** [comment]
@benjaoming, just for a record, I did not see that debconf dialog **when I declined** to run KA LIte as the system service (on startup). If one chooses to do so in the previous step, the dialog appears a-OK!

**Comment by benjaoming** [comment]
@radinamatic the choice of username was only shown for people installing the init.d script, this is now fixed! :)

**Comment by benjaoming** [comment]
Fixed in #222 that is :)

**Comment by radinamatic** [comment]
:+1:  :)

**Comment by benjaoming** [comment]
Notice now how ka-lite-gtk appears now in Software Center - @jamalex might be of interest to you too

![screenshot from 2015-12-01 01 05 54](https://cloud.githubusercontent.com/assets/374612/11488556/cf15a6ba-97c7-11e5-9161-e56c52600eee.png)

**Comment by benjaoming** [comment]
Also, this dialogue now appears -- feature or bug? @jamalex @aronasorman 

I would consider it a potential feature and since it's pre-filled, users can just skip it...

![screenshot from 2015-12-01 01 08 20](https://cloud.githubusercontent.com/assets/374612/11488592/156d98de-97c8-11e5-88f5-da8972697b6a.png)

**Comment by radinamatic** [comment]
Wasn't `ka-lite-gtk` option available for a while? If I remember well, since sometime this last summer?

**Comment by benjaoming** [comment]
@radinamatic no afaik the way it's displayed now is a result of:

1) ka-lite-gtk is available in the ka-lite PPA
2) ka-lite-gtk is a "suggests" not a "recommends", so before it was silently installed automatically when installing from the ppa

**Comment by radinamatic** [comment]
I don't know the exact difference between "suggests" and "recommends", but I'd swear it was there at some point during my testing, and in USC it did not install unless expressly checked... I'll see if I can maybe dig some old screenshots.

**Comment by EdDixon** [comment]
@radinamatic in previous builds it was packaged in the deb bundle (unintentionally I think) along with the R-Pi build but @benjaoming has since resolved that issue. However I am still expereincing installation failures when installing by simply double clicking the deb package opening it in USC as before. 

I want to add that multiple attempts at installing using that method on the latest 0.15-ubuntu4 seems to have different results with the first simply starting and then stopping with no feed back, the second starting and showing the progress bar and then stoipping with no feed back, the third starting showing the progress bar which eventually fills almost to completion when the installer just seems to stall out. I have left it in this state up to an hour with out change before crashing out of it.

**Comment by benjaoming** [comment]
@EdDixon 
> in previous builds it was packaged in the deb bundle (unintentionally I think) along with the R-Pi build

No, it was never bundled. It was in the same PPA, and "Recommends" makes it install as a dependency if its available. "Suggests" is different in that it will only show a message to the user.

@EdDixon 
> different results with the first simply starting and then stopping with no feed back,

Probably has to do with libgtk2-perl, see earlier posts. Stuff still breaks when installing in USC and this library isn't present. This is probably not going to go away, hence there's a task in this issue about documenting it.

**Comment by EdDixon** [comment]
@benjaoming just to clarify what I mean by "bundled" is that all 3 were being installed to the Debian system previously using "dpkg -i" without PPA. I have a screen shot here somewhere that clearly shows that happening but I know it has since been fixed. So that is no longer an issue anyway, just that I think that maybe what @radina is referring too when after installation she would have the gtk gui without having separately installed it. It happened to me as well and that's when I looked to see what else was getting installed and discovered all 3 pkgs where being installed (R-Pi, Ka-Lite, and the gtk gui) at that time. Keeping in mind, it was still very much in development then.  I do agree that it is a very minor thing anyway, we have many better (IMHO) ways for the user to use to do the installation. We just need to let them know through documentation that this is not one of them :)

**Comment by benjaoming** [comment]
@EdDixon 
> just to clarify what I mean by "bundled" is that all 3 were being installed to the Debian system previously using "dpkg -i" without PPA.

That was never the case. `dpkg -i` installs no dependencies, which is core of why we test both `dpkg -i` and `apt-get install`.

I think we should dedicate comments on issues to the specific topic: Ubuntu Software Center.

> So that is no longer an issue anyway, just that I think that maybe what @radina is referring too when after installation she would have the gtk gui without having separately installed it. It happened to me as well and that's when I looked to see what else was getting installed and discovered all 3 pkgs where being installed

Sorry, but did I mis-communicate something? This is exactly why I was showing the former screenshot and explaining the difference between Suggests and Recommends that was changed :)

Let me know if you need these concepts explained more thoroughly. I think we should step through them during a Hangout, maybe after today's standup.

**Comment by EdDixon** [comment]
@benjaoming I guess I am missing somthing here and we should then, after the standup is fine. In the meantime I will try to find those screenshots. I have been thinking that my pointing out that problem back then (and I am not sure how long ago it was) lead to the changes that seperated them into the packages they are now? I guess not LOL so sure lets take a closer look. It would be great if we can support this installation method in the upcoming release. As I understand it the focus is on the installers this round.

**Comment by benjaoming** [comment]
Btw the Launchpad bug about missing libgtk2-perl has been accepted in Ubuntu 100 Papercuts, and so the fix might actually be released for old supported Ubuntu dists like Trusty.

**Comment by benjaoming** [comment]
It seams that Ubuntu Software Center doesn't provide an env from which to tell the current user:

```
DBUS_STARTER_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
DPKG_MAINTSCRIPT_PACKAGE_REFCOUNT=1
STATE_FILE=/tmp/kaliteinstall.state
DEBIAN_HAS_FRONTEND=1
DPKG_MAINTSCRIPT_NAME=postinst
PERL_DL_NONLAZY=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBCONF_PIPE=/tmp/aptdaemon-s10q8j/debconf.socket
DPKG_MAINTSCRIPT_ARCH=all
PWD=/
LANG=en_US.UTF-8
DBUS_STARTER_BUS_TYPE=system
SHLVL=1
DPKG_ADMINDIR=/var/lib/dpkg
DPKG_RUNNING_VERSION=1.17.5
DEBCONF_REDIR=1
APT_LISTCHANGES_FRONTEND=none
DEBIAN_FRONTEND=passthrough
APT_LISTBUGS_FRONTEND=none
DPKG_UNTRANSLATED_MESSAGES=1
DPKG_MAINTSCRIPT_PACKAGE=ka-lite
_=/usr/bin/env
```

On the other hand, we can rely on the `users` command to tell us who's logged in:

    benjamin benjamin benjamin benjamin

**Comment by benjaoming** [comment]
There we go :)

![screenshot from 2015-12-02 19 00 28](https://cloud.githubusercontent.com/assets/374612/11539376/ff092bca-9926-11e5-8aec-7b780c95867b.png)

**Comment by benjaoming** [comment]
Docs fix is now up!

http://ka-lite.readthedocs.org/en/0.15.x/installguide/install_all.html#linux

Closing this, and then if the Launchpad bug is fixed, we can make amends.
