### ISSUE TITLE
 Documentation page is not loaded in IE11 on Win8.1

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#178]
**Branch:** 0.15.x.

**Windows installer:** kalite-setup-0.15.0--9-18-2015.exe

**Platform:** IE11 on Windows 8.1

**Expected Behavior:** Fix the Documentation page returns 404 Not found. 

**Current Behavior:** 
When you navigate to the Documentation link, the documentation page returns 404 Not found. 
The path `/static/html/index.html` was not found
![demo-open-documentation](https://cloud.githubusercontent.com/assets/4099119/10068433/e5380224-62d6-11e5-96b2-0df916471a54.gif)

**Steps to reproduce:**
>1.  Navigate to Login page and login to admin.
>1.  Navigate to the user account tab then click the `Documentation` link.
>1. Notice that the Documenation page return "404 not found".

**Comment by MCGallaspy** [comment]
Does a restart resolve this? Were you prompted to restart after completing installation?

**Comment by MCGallaspy** [comment]
Can you also paste the traceback here?

**Comment by arceduardvincent** [comment]
Hi @MCGallaspy, Yeah it prompt me to reboot.

Installer traceback error:
```python
Traceback (most recent call last):
  File "C:\Program Files\KA Lite\ka-lite\python-packages\cherrypy\_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Program Files\KA Lite\ka-lite\python-packages\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files\KA Lite\ka-lite\python-packages\cherrypy\_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files\KA Lite\ka-lite\python-packages\cherrypy\_cptools.py", line 170, in handle_func
    raise cherrypy.NotFound()
NotFound: (404, "The path '/static/html/index.html' was not found.")
```

**Comment by djallado** [comment]
I also observed the using IE10 in windows 7, and my installer is from: http://field.learningequality.org/KALiteSetup-0.15.0--9-25-15.exe.

here's my snapshot:

![screen shot 2015-09-29 at 4 36 43 pm](https://cloud.githubusercontent.com/assets/8664071/10159079/a4eb9c9e-66c8-11e5-99bc-d619b334622c.png)

It works fine using IE10 on windows 8.

![screen shot 2015-09-29 at 4 41 46 pm](https://cloud.githubusercontent.com/assets/8664071/10159131/14610438-66c9-11e5-9c43-c7c44734e38e.png)

**Comment by MCGallaspy** [comment]
Attempting to replicate.

**Comment by MCGallaspy** [comment]
Able to replicate on Windows 7, but not Windows 8. That's a start, but I'm still scratching my head.

**Comment by MCGallaspy** [comment]
Okay, I manage to determine that this is due to the setting `STATIC_ROOT` pointing to user's data directory (`~/.kalite/httpsrv`) when `IS_SOURCE=False` (as with installation via the Windows installer), but the docs are in this case included in the source. For me, I wasn't able to replicate it running from source presumably because the staticfiles had been copied into my user data directory.

**Comment by MCGallaspy** [comment]
Static files from the source directory (in this case the docs) will be copied to the user's data directory when the `collectstatic` management command is run, which used to happen every time the server was started (see https://github.com/learningequality/ka-lite/commit/d1e042df7ecae631b538a981f520deda74dbde3a). It's also run during setup, but presumably because Windows ships with an up-to-date database file, setup is not run. Maybe the best solution here is to force Windows to run the non-interactive `setup` at least once.

**Comment by MCGallaspy** [comment]
`setup` *should* be run at least once -- I'm guessing [this LOC](https://github.com/learningequality/installers/blob/master/windows/installer-source/KaliteSetupScript.iss#L419) is the stinker, probably runs ok on Windows 8 & greater but fails somehow on Windows 7 and lower. Testing my hypothesis.
