### ISSUE TITLE
Mac installer to use DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#206]
A filthy hack was introduced in this commit and it should be cleaned up by means of a special settings module:

https://github.com/learningequality/ka-lite/pull/4510/files#diff-f5909fd34301a5f428e9da26bb5d1df0R37

I'm thinking we should use `DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP=True` if that's the fundamental thing we want to achieve especially for the Mac.

Either the module should included in the Mac installer or by creating `kalite.project.settings.osx` -- I think the installer should be 100% responsible for this, since the setting is mainly regarding the specific setup that we distribute through the installer.

Can also be closed in case we figure out a better more universal cache invalidation mechanism.

@cpauya if this is easy to implement, go for it, otherwise push it to 0.16

**Comment by aronasorman** [comment]
Note that this hack won't be necessary for 0.16 -- we have a totally different system for cache invalidation that invalidates the need for the hack :)

**Comment by aronasorman** [comment]
So this is really only a temporary thing.

**Comment by benjaoming** [comment]
Yup, I guess the main benefit from solving this would be if the Mac installer got its own bundled settings module where you can configure stuff like `DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP` whenever needed.

**Comment by cpauya** [comment]
We removed this "capability" for the Mac installer to spit-out it's own settings file during installation because there's already a `~/.kalite/settings.py` file from the setup process.  That's the settings file that the Mac installer should touch after setup.  

However, I tried that before as per https://github.com/learningequality/ka-lite/issues/4483#issuecomment-143113453 and found that it doesn't work.  We will revisit the [Sidebar is not updating downloaded videos](https://github.com/learningequality/ka-lite/issues/4483) this week just to make sure.  

Now, in case it still doesn't work, then I think we should just file an issue that says something like "remove  hack to show warning for OSX server on video download page".  Unless there's another solution?

**Comment by rtibbles** [comment]
If you use DO_NOT_RELOAD_CACHE_AT_STARTUP you still need to restart the server to have downloaded videos show up in the sidebar, so neither setting actually solves the issue.

The issue itself will be solved in 0.16, where we are now invalidating caches in a much less resource hungry way.

**Comment by benjaoming** [comment]
So this is solved, great, go team :)
