### ISSUE TITLE
Support OS X "El Capitan".

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#208]
Updating the MAC to the latest OSX version (EL Capitan) lost the environment variables causing the attached error message. Trying to use the preferences dialog box to reset the app also fails with a notification from KA Lite. Also the notification indicates that a plist or symlinked kalite executable was not deleted before this error message was issued. A reinstall at this point seems to be the only solution.

![2015-10-05_09-20-04](https://cloud.githubusercontent.com/assets/4349806/10285742/75cb7ad2-6b47-11e5-943d-511a04d4787a.png)

**Comment by aronasorman** [comment]
I believe [SIP](https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html) in general will just introduce headaches for us. Let's put this in as a 0.16 issue as this needs further investigation. cc @cpauya.

**Comment by aronasorman** [comment]
Note that @arnoan successfully installed KA Lite on El Capitan, so a fresh install still works at least.

**Comment by cpauya** [comment]
I've just verified this with latest installer "KA-Lite-Monitor-0.15.x--2015-10-06a.dmg" on an OSX - El Capitan - fresh install.

![screenshot 2015-10-06 01 14 37 copy](https://cloud.githubusercontent.com/assets/175580/10287913/68cdff04-6bc8-11e5-8b2d-810ea1f0cf82.png)

Note the error on the Console app:

> 10/6/15 1:13:50.000 AM kernel[0]: Sandbox: ln(35116) System Policy: deny(1) file-write-create /usr/bin/kalite

This confirms the [System Integrity Protection (SIP)](https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html#//apple_ref/doc/uid/TP40016227-SW1) mentioned by @aronasorman above.

@arnoan - may I ask which OSX installer did you use on your El Capitan?

**Comment by aronasorman** [comment]
Ah right - I remember @arnoan mentioned that he disabled SIP. Heh. @arnoan can you confirm?

**Comment by EdDixon** [comment]
Confirming that disabling SIP works to get around the installation problem here.

**Comment by arnoan** [comment]
@cpauya I used the ka-lite › 0.15 › #4 installer. (The one compiled by Aron last Thursday)
@aronasorman Yes, that's right. I disabled SIP immediately after the upgrade to OSX 10.11 so I would not have noticed any issues related to that.

With SIP disabled I encountered no issues. (Other than having to extract assessment items manually due to my pre-existing .kalite folder.)

**Comment by aronasorman** [comment]
I'm changing this to be our "El Capitan support" issue.

**Comment by cpauya** [comment]
**Update**

I have tested that symlinking the `kalite` executable to `/usr/local/bin/kalite` will make the OS X .app work on OS X El Capitan.

However, video and language pack downloads doesn't work because `/usr/local/bin` is not included in the `PATH` environment variable of cron as per http://superuser.com/questions/164394/how-to-set-cron-path-globally-i-e-for-all-users-permanently.  The `PATH` for cron is `/usr/bin:/bin`.

I've also tested this using a simple cronjob with this content `0-59 * * * * echo "Hello World: $PATH" > /tmp/cron.txt` and checking out the output on `/tmp/cron.txt` which yields `Hello World: /usr/bin:/bin`.

So, will be exploring this some more.

**Comment by cpauya** [comment]
This is now fixed on latest `develop` branch.  

Release for 0.16.x will have support for El Capitan.

@EdDixon I think we can close this now?

**Comment by EdDixon** [comment]
@cpauya I think so. I wish there was a clear and easy way to inform the user of the problem and workaround for versions 0.14 and below but since even that will not work with 0.15 and 0.16 should resolve the problem maybe we should just remove prior versions from availability all together for OSX to prevent them from running into this issue to begin with (keeping in mind 0.13 and 0.14 were new at some point within just the past year and now being treated as legacy)?  Just a use case I can see happening (not often) but, how can we best handle this for the user who decides to reinstall after an OS upgrade for example?

**Comment by cpauya** [comment]
@EdDixon We have a WIP PR for a release notes file in the OS X installer at https://github.com/learningequality/installers/pull/323 -- I think this will help the user in deciding which versions to use (or which versions to jump to when upgrading).

Although it's normal for a user to install the latest released version, we must keep the released versions in cases where some users actually downloaded and used them.  This way we also have reference versions for our testing and upgrade scenarios.

**Comment by cpauya** [comment]
This was already fixed in the `develop` branch.
