### ISSUE TITLE
Windows installer should not rely on deprecated scripts

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/installers#25]
We're removing deprecated `bat` scripts from the project to avoid confusion. The only supported command line interface is `bin/kalite` or `bin/windows/kalite.bat`. Let's make sure the Windows installer doesn't rely on any of the scripts we're now deprecating.

**Comment by EdDixon** [comment]
A git update from 12.11 to 13.x does leave those scripts currently. Issue has not been seen in other 13.x installations methods. Once the system command path issue is resolved we should not need to rely on the partial paths to the kalite command and hopefully will never need to call them directly as in "bin/windows/kalite.bat"

**Comment by EdDixon** [comment]
On testing a recent 13.x windows installer candidate I did confirm that the installed system relies on the start and stop batch files for that functionality as well. Replicate by simply removing them from the ka-lite folder. Without them or a fix for the path problems in the kalite command the user has no way to start or stop the server?

**Comment by ruimalheiro** [comment]
At the moment, both, the windows installer and the GUI relies on those scripts. We can let the windows GUI handle it (like it was before we change to those scripts), or we can communicate with the kalite bin (which I think would be the simplest and cleaner approach). If so, I just need to see the interface.

**Comment by EdDixon** [comment]
@ruimalheiro  the kalite command seems to be having some pathing issues regardless how it is launched at the moment so it can not start or stop the service which will need to be resolved first I think? But I do agree that would be the prefered solution! All kinds of additional notes in the testing room :) Thanks,

**Comment by EdDixon** [comment]
Just to clarify this issue involves older scripts now no longer used, which provided functions such as starting and stopping the ka-lite server etc. We have since switched to a much more robust method of dealing with these functions but this switch has regretfully reduced some older functionality. For example selecting the start on boot option will work with newer WIndows systems but fails on XP as the server will not start with that option selected when the machine first boots WIndows XP. This example does not affect WIndows 7 or higher operating systems.

**Comment by benjaoming** [comment]
All these scripts are gone and deleted! So it can't possibly rely on them, otherwise it's broken :)

Closing this for now and moving @EdDixon 's latest comment to #106

Great work everybody! :)
