### ISSUE TITLE
Mac OS X .app file

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#3]
<a href="https://github.com/aronasorman"><img src="https://avatars.githubusercontent.com/u/191955?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aronasorman](https://github.com/aronasorman)**
_Thursday Dec 04, 2014 at 02:36 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/2758_

----

So, we want to move away from git-based installations for Unix systems, and use the native installation methods.

This issue is for OS X's .app package. The ideal is to have a script that receives a directory argument and outputs a .app file which the user can drag and drop to the ~/Applications/ folder.

Note: this should be in a separate repository, but I'm just putting it here so we can all monitor it.

**Comment by aronasorman** [comment]
Any updates here @cpauya?

**Comment by cpauya** [comment]
Hi @aronasorman - sorry was not able to work with an implementation of this yet.  

I looked at the [appify script](https://github.com/learningequality/installers/issues/3#issuecomment-66652793) you mentioned above have [issues running on OS X versions 10.7 or later](https://gist.github.com/mathiasbynens/674099#comment-1361769).  I think the next alternative to it is [appify-ui](https://github.com/subtleGradient/Appify-UI).

I've updated [my Trello cards](https://trello.com/b/85rlwGiP/cyril-s-tasks) on my findings re OSX users.  I've found the [Adium user stats](https://www.adium.im/sparkle/#osVersion) and so far decided that we need to support at least OSX Lion 10.7 onwards for this .app.

Hope to get something this weekend.

**Comment by benjaoming** [comment]
@cpauya 

Due to learningequality/ka-lite#2757 I am cleaning up the scripts/ dir a bit and introducing a new executable for doing things. It's expected that all platforms use the `kalite` executable as the only CLI.

scripts dir:
https://github.com/benjaoming/ka-lite/tree/kalite-single-executable/scripts

bin directory with the new executable:
https://github.com/benjaoming/ka-lite/tree/kalite-single-executable/bin

I hope this will help building cross-platform stuff. I'll work on the `kalite` first priority for now, and I'll let you know as soon as it's ready to use. Also, I'll make sure to rebase against the mainline develop branch so you can use my branch to test against if you like :)

**Comment by cpauya** [comment]
Thanks @benjaoming - that'll hopefully consolidate the scripts for running KA-Lite.

**Comment by cpauya** [comment]
Just an update that I've been trying to make an .app of `ka-lite` and `ka-lite on pyrun` using [Platypus](http://sveinbjorn.org/platypus) -  "It creates native Mac OS X applications from interpreted scripts such as shell scripts or Perl, Ruby and Python programs".

Please note that we aim to make a script to do what Platypus can do now and am still working on packaging `ka-lite` as an .app... see screenshots for examples.

**Platypus app in action**
![screenshot 2015-01-19 20 02 21](https://cloud.githubusercontent.com/assets/175580/5800180/832631d8-a016-11e4-81cc-eafdc47fb5fa.png)

**Basic Platypus status menu app - 364KB**
![screenshot 2015-01-19 20 00 18](https://cloud.githubusercontent.com/assets/175580/5800185/954636b0-a016-11e4-8738-0d7095846ca2.png)

**Attempt to package ka-lite as an app**
![screenshot 2015-01-19 20 04 53](https://cloud.githubusercontent.com/assets/175580/5800194/ce54a932-a016-11e4-8798-482e09886310.png)

/cc: @aronasorman

**Comment by cpauya** [comment]
The app will have a status menu that will:

1. monitor the status of the server
2. change it's icon according to server status (green for running, red for stopped)
3. menu entries to start, stop, open in browser, options, etc.  

Refer to the [Cross-platform design of the tasktray icon launcher menu](https://github.com/learningequality/installers/issues/6#issuecomment-70432087)

Steps:

1. Create an .app for ka-lite that uses PyRun maybe using [Platypus](http://sveinbjorn.org/platypus)
2. Package this into a .dmg file.

**Comment by cpauya** [comment]
Was able to run ka-lite with Platypus
![screenshot 2015-01-22 09 54 45](https://cloud.githubusercontent.com/assets/175580/5849243/d0288054-a21d-11e4-8ecf-9dd43c636032.png)

But my issues with Platypus are:

 1. The whole ka-lite repo + contents are packaged into one "ka-lite.app" - roughly 469MB+ from my end.  We need to find a way to separate the repo/source from the content - which @aronasorman  suggested is to create a `local_settings.py`.
 2. We need an executable or binary like `/usr/bin/kalite` so we can run the equivalent ka-lite management commands (or their equivalent) on the terminal because (as per item 1 above) - there's no user-friendly way to access the `manage.py` files which is most likely inside the `/Applications/ka-lite.app/Contents/Resources/*`.
 3. Use of the binary from item 2 above for the status menu entries (Start, Stop, Open in Browser, etc) because the status menu that Platypus creates will execute the script when the menu item is clicked and show the output as menu items.  So we cannot execute scripts for the menu items on Start, Stop, etc like a typical menu system should be.

I have started to use Objective-C to build the status menu items and here's the initial output.
![screenshot 2015-01-22 10 25 43](https://cloud.githubusercontent.com/assets/175580/5849489/120dd962-a221-11e4-9f46-24071c06068d.png)

Am also looking to use [PyObjC](http://pythonhosted.org/pyobjc/core/intro.html) and [Py2App](http://pythonhosted.org//py2app/index.html) as fit.

**Comment by cpauya** [comment]
@aronasorman 

One issue that we need to consider aside from separating the content from the .app is where will the languagepacks/translations be saved?  Coz they are saved on the `/kalite/locale/` folder as per `settings.py`.

So the locations for the content and language packs must be "asked" from the user during installation.

**Comment by jamalex** [comment]
@cpauya Does an .app actually bundle to a single file? I thought I remember somebody telling me it's really a folder, though it looks like a file through Finder.

The reason I ask is that we also want to be able to update the ka-lite Python codebase internally (via a signed zip bundle), so we don't want the other files all hardcoded into a single file either.

**Comment by cpauya** [comment]
No @jamalex the .app is a folder that contains our codebase and content.  In Finder, you can right-click on the .app and select `Show Package Contents` to navigate its contents.

And yes, I understand we want to be able to update our codebase too, I've been playing with the `settings.py` inside the .app to see how it behaves.

Although to be honest, I have no idea how to update the codebase inside the .app but I've read about [Sparkle](http://sparkle-project.org/).

**Comment by cpauya** [comment]
Oh, perhaps you meant to say `python manage.py update` that will "Create a zip file with all code, that can be unpacked anywhere."?

**Comment by jamalex** [comment]
Ok, great! Yep, that should be fine then.

We don't need to worry about the internal updating process yet (as it doesn't really exist, other than a temporary version @aronasorman made for updating via git); for now, we just need to make sure that installing a new dmg/.app installer will properly update the installed version, keeping the content and database around, and migrating the database.

In the future, the update process will be built into the KA Lite web interface and done by Python code itself. I just wanted to make sure we were designing towards something that would work well with that.

Looking awesome!!! :100:

**Comment by aronasorman** [comment]
Btw we'll need to look into signing our installer as well: https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html

**Comment by cpauya** [comment]
We are now able to bundle the `ka-lite` source inside the .app and been using @benjaoming's `kalite` executable as per https://github.com/learningequality/ka-lite/issues/2757.  Here's the uploaded [KA-Lite Monitor.app](Cross-platform design of the tasktray icon launcher menu) on Google Drive.

The menu entries for start, stop, open in browser are also working but they need to be improved and their icons set accordingly.  Example: If running, the Start item must be disabled.

Some screenshots:
![screenshot 2015-01-29 10 58 14](https://cloud.githubusercontent.com/assets/175580/5951728/f79b3df6-a7a5-11e4-82f2-477653ec9b7a.png)

![screenshot 2015-01-29 10 58 34](https://cloud.githubusercontent.com/assets/175580/5951730/fc4cb802-a7a5-11e4-83cf-b4d03282bb54.png)

ToDos:
- [x] Package ka-lite source inside the .app
- [ ] Package and use pyrun inside the .app
- [ ] Generate a .dmg file
- [ ] Use custom images as icons (running, stopped, error?) as per [Cross-platform design of the tasktray icon launcher menu](https://github.com/learningequality/installers/issues/6#issuecomment-70432087) - @aronasorman do we have those icons somewhere?
- [ ] Run `setup_mac.command` on first run
- [ ] Generate a `local_settings.py`

**Comment by cpauya** [comment]
Updates:
* We now check if there's a `local_settings.py` and if there's none, we copy the `local_settings.default` over as `Contents/Resources/ka-lite/kalite/local_settings.py`.
* We also check if there's no database yet then run `kalite manage setup --username=admin --password=password123 --noinput`

Issue:
* @djalldo tried to put his pyrun binary for the `KALITE_PYTHON` environment variable and tried `kalite manage shell` but instead of using pyrun, it used the OS X python version instead.  Will resume on this tomorrow.

@aronasorman Should I commit the source on this repo or to another specific for "OS X installer" repo?

**Comment by jamalex** [comment]
> We also check if there's no database yet then run kalite manage setup --username=admin --password=password123 --noinput

In the Windows installer, we ask the user to set the superuser username and password. Probably want to do the same here?

> tried kalite manage shell but instead of using pyrun, it used the OS X python version instead

`shell` tries to find IPython and use that if available, falling back to the standard python shell if not, so it probably searches and finds the system python in the process of looking for the interpreter to use.

**Comment by aronasorman** [comment]
@cpauya you can put the code in the installers repo, no need to create a separate one.

**Comment by benjaoming** [comment]
@cpauya great work! I would like to tip the `kalite status` command which
will give you an exit status code indicating the status of kalite
(running/stopped/startup failure etc). You can use this to schedule polling
for status and setting the notification icon + hover text?

Different known statuses are listed in kalitectl.py but there might be more
added over time, so I suggest that 0 = started, 1 = stopped, all other =
some kind of failure icon.

A suggestion (timing should be adjusted)

First 2 minutes after hitting start, `kalite status` is polled every 5
seconds
First time that `kalite status` returns status 0 (Running), start polling
only every 5 minutes.

Explanation: `kalite status` is a little more expensive when determining if
kalite is running, because it makes an HTTP call to see that the server is
in fact alive.

**Comment by cpauya** [comment]
Good ones @benjaoming, I have added your notes on the list. :smile_cat: 

**Plans for next Iterations**
- [ ] Update the status icon as discussed.
- [ ] Have a Preferences menu item to display preferences dialog (see Dropbox screenshot below).  
    - [ ] User values for admin user account, path to database, contents, language packs, etc.
    - [ ] This will also display when `setup` is ran to prompt user and show logs - and some values will go in the `local_settings.py`.
    - [ ] Other content/tabs we can agree on.
- [ ] Poll `kalite status` based on timings at Preferences dialog and update status icon.

![screenshot 2015-01-30 08 17 11](https://cloud.githubusercontent.com/assets/175580/5968932/8953730a-a858-11e4-8649-b390bbafdca5.png)

**Comment by benjaoming** [comment]
:+1: Great idea about preferences!!

**Comment by aronasorman** [comment]
Integrating this with the build server now -- you need to be in the same directory as `setup.sh`. You can't execute it from anywhere.

**Comment by aronasorman** [comment]
Apparently I require the entire XCode application. *shakes fist at Apple*

**Comment by cpauya** [comment]
Sadly yes @aronasorman - as of now, we need Xcode to build the .dmg.  I will look if we can generate a `Make file` out of the Xcode project files later - which is part of the "Try to build Xcode project on Linux" task.
