### ISSUE TITLE
Include Uninstall button in the Preferences dialog.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#332]
**Branch:** Develop

**Target:** 0.16.x

**Current Behavior:** There is no uninstall button in the `Preferences` dialog. 

**Expected Behavior:** We must have an uninstall button on the preference dialog so the user can easily locate the uninstall button.

**Checklist:**
- [x] Create a  `Uninstall` button 
- [x] Modify uninstall script that support the deleting of `$KALITE_HOME` without user confirmation.
- [x] Modify uninstall script that support uninstalling without user confirmation. 
- [x] Add a checkbox to "Delete the KA Lite data folder."

**Comment by cpauya** [comment]
@amodia Can you add a checkbox to "Delete the KA Lite data folder." next to the uninstall button?  

Then make sure to use the `KALITE_HOME` environment variable if it exists or default to `$HOME/.kalite/`.

@arceduardvincent Reminder to be very careful with this because inside the uninstall script is a `sudo rm -rf <path>` command.

**Comment by cpauya** [comment]
Fixed in #336.
