### ISSUE TITLE
Manually test 0.15 -> 0.15.1 -> 0.16 upgrade path for Debian

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#353]
@radinamatic I've moved this issue so we can get the docs instructions up.. they're supposed to work so it's an issue if they don't.

**Comment by radinamatic** [comment]
Ok, agreed!

**Comment by radinamatic** [comment]
1. Install `ka-lite_0.15.0-0ubuntu4_all.deb`
2. Add assessment items during `kalite manage setup` (since it was unsuccessful during install - see #356) 
3. During upgrade to `ka-lite_0.15.1-0ubuntu2_all.deb`, installer requires to download assessment items again.

It is of course possible to entirely skip this step, but user will be reminded to do it during `kalite manage setup` after the upgrade, and it seems entirely unnecessary, since assessment items that they would download/add at this point would be the same ones they already installed during 0.15.0 install, correct? I'm just wondering if it's possible to check if the assessment items are already present and skip that step during minor version upgrades? @benjaoming

**Comment by benjaoming** [comment]
It's a catch22.. the current version that's being uninstalled can't predict if the new version will use the same assessment items or not. Therefore it deletes them :(

**Comment by radinamatic** [comment]
Weird, I was under impression I had the same assessment items "inherited" from 0.15.0 once I updated with `ka-lite_0.15.1-0ubuntu2_all.deb`. I'll recheck that VM tomorrow to confirm (or deny :wink:).

**Comment by benjaoming** [comment]
With ka-lite-bundle you do because they're bundled and arrive with your next ka-lite-bundle .deb

But all files generally just remove the system assessment item dir:

```bash
kalite_purge()
{

    # Remove assessment items since they might be overwritten by other packages
    rm -rf /usr/share/kalite/assessment

    # Remove service file using `ucf` (checking whether `ucf` is still available first)
    if type ucf >/dev/null 2>&1;
    then
        ucf --purge "/etc/init.d/ka-lite"
    fi

    # Remove service file by hand (in case the above failed somehow)
    rm -f "/etc/init.d/ka-lite"

}
```

**Comment by radinamatic** [comment]
Other potentially improvable aspects for the .deb installer - not 0.15, but for 0.16 if we continue to make available both "minimal" and bundled version.

Installing "minimal" .deb:

```
didi@didi-VirtualBox:~/Downloads$ sudo dpkg -i ka-lite_0.15.0-0ubuntu4_all.deb
[sudo] password for didi:
Selecting previously unselected package ka-lite.
(Reading database ... 239027 files and directories currently installed.)
Preparing to unpack ka-lite_0.15.0-0ubuntu4_all.deb ...
Unpacking ka-lite (0.15.0-0ubuntu4) ...
Setting up ka-lite (0.15.0-0ubuntu4) ...

Creating config file /etc/init.d/ka-lite with new version
Processing triggers for man-db (2.7.4-1) ...
didi@didi-VirtualBox:~/Downloads$ 
```
At this point user may not remember well what are they supposed to do, since the command finishes without visible instruction. In truth, user was advised in previous window to run `kalite manage setup`, but it is not possible to return to it from here, and for further clarity, I would suggest repeating this instruction. So, maybe end the previous output as:

```
...
Creating config file /etc/init.d/ka-lite with new version
Processing triggers for man-db (2.7.4-1) ...

Thank you for installing KA Lite! To finish setting up the server software, run the following command:

kalite manage setup

didi@didi-VirtualBox:~/Downloads$ 
```

**Comment by radinamatic** [comment]
**ka-lite-bundle_0.16-a3-0ubuntu1_all.deb**

Reiterating the previous post with one caveat: I misunderstood that the server is actually already running at this point, so my suggestion would be:

```
...
Creating config file /etc/init.d/ka-lite with new version
Processing triggers for man-db (2.7.4-1) ...

Thank you for installing KA Lite! Server is already running and you can access it with your browser at:

http://127.0.0.1:8008/

didi@didi-VirtualBox:~/Downloads$ 
```

**Comment by benjaoming** [comment]
@radinamatic you can't write user messages like that, they will end up inside other installation outputs. Take for instance this example: `sudo apt-get install ka-lite some-other-package`, the other package would get installed after ka-lite.

**Comment by benjaoming** [comment]
Not sure where this one landed, @radinamatic do you think we can close it?

**Comment by radinamatic** [comment]
@benjaoming Yes, I think we can close this. 

Output could be slightly more user-friendly for a non-admin level user, but if it's not possible to insert some kind of output like the one I suggested above, I'm short of ideas... :stuck_out_tongue:
