### ISSUE TITLE
Higher-priority OSX installer tweaks

### ISSUE THREAD

**Issue by jamalex** [learningequality/installers#373]
## Summary

- [x] At the end of the beautiful installer GUI wizard, tell the user what to do next. E.g. "Now that KA Lite is installed, you can start/stop the server, and launch the browser, from the leaf icon in your task tray" (or whatever that row of little icons is called on a Mac)
- [x] Launch the KA Lite app as soon as the installer finishes.
- [x] Auto-start the server whenever the KA Lite app is loaded.
- [x] Have the default behavior be to auto-launch the KA Lite app at boot (but still allow them to disable it, by unchecking that box under preferences)

## Branch or installer

@aronasorman demoed the latest 0.16.x candidate OSX installer to me (yesterday).

**Comment by cpauya** [comment]
Thanks for checking it out @jamalex - will prioritise these today.

**Comment by cpauya** [comment]
Hi @jamalex - I've tried customising the GUI wizard dialog but can't find an easy way to insert the text to "tell the user what to do next".

So I moved to the following tasks instead:

* [x] Auto-load the KA Lite app on login (we don't do this from originally, but it can be set on the Preferences dialog)
* [ ] Launch the KA Lite app as soon as the installer finishes.
* [ ] Auto-start the server whenever the KA Lite app is loaded.

I've discussed these during sync-up with @aronasorman today.  With those tasks, I think we can already do away from "telling the user what to do next" on the GUI wizard because:

1. After the installer finishes, we will auto-launch the application.
2. KA Lite is auto-started when the app is loaded.
3. Each step has notifications to tell the user what's going on.

So after a successful installation, user can expect a notification that "KA Lite is running and can be accessed using the 'Open in Browser' menu".  

I will get these done by Wednesday so we have time to test.  I hope that's fine?

**Comment by cpauya** [comment]
Hi @jamalex / @radina - pls use the [build 89 at Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-89) to test this issue.

**Comment by amodia** [comment]
@cpauya I tested the [build 89 at bamboo](http://dungeon.learningequality.org/browse/KL-MT16-89) on OS X mavericks. The first installation will fail. 

Here's the screenshot.
![screen shot 2016-03-21 at 11 59 58 am](https://cloud.githubusercontent.com/assets/8663934/13910511/5a607f72-ef5e-11e5-95f2-7e4cc389759d.png)

**Comment by djallado** [comment]
I tested this also and here's the screenshot with console logs.
![fail](https://cloud.githubusercontent.com/assets/8664071/13910582/8fa01890-ef5f-11e5-853e-8d5bcbe81a04.png)

**Comment by cpauya** [comment]
Thanks for the test @amodia / @djallado - will submit a fix after testing today.  @radinamatic Please hold-off in testing this.

**Comment by cpauya** [comment]
Please use [build 93 on Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-93) to test this. 

/cc: @radinamatic @aronasorman

**Comment by benjaoming** [comment]
@cpauya this seems fixed? :)

**Comment by cpauya** [comment]
Yes @benjaoming - closing now, thanks. 😸
