### ISSUE TITLE
Bundle KA Lite into PyRun

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#4]
<a href="https://github.com/aronasorman"><img src="https://avatars.githubusercontent.com/u/191955?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aronasorman](https://github.com/aronasorman)**
_Thursday Dec 04, 2014 at 19:11 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/2761_

----

[PyRun](https://www.egenix.com/products/python/PyRun/) is the most promising way right now for us to bundle Python to Unix systems. We should see if we can do it for KA Lite and see if it runs. 

If it does work, let's create a script that outputs KA Lite + PyRun. We should also determine what settings we need to change in order for it to work perfectly. These changes would then go to the `local_settings.py` inserted by the build server.

**Comment by aronasorman** [comment]
@cpauya can you give an update on where you are with testing out PyRun?

**Comment by cpauya** [comment]
We can use PyRun as a `virtualenv` replacement as I've tested earlier.

But since packaging KA-Lite into PyRun under OSX 10.10.1 doesn't work well (compiler issues which will take a while) - what I will do now is to create a script to package them together and make sure that KA-Lite uses PyRun (the Python version of PyRun) instead of the system Python.
