### ISSUE TITLE
Footer shows inappropriate version 

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#405]
## Summary

The KA Lite version is still 0.16.3 and year is 2015.

## Branch or installer

 - Installer: OSX
 - Version: 0.16.x 

or:

 - Branch: 0.16.x

## Screenshots
![footer](https://cloud.githubusercontent.com/assets/8664071/16132076/4b5349d0-3444-11e6-93c0-e8ef9782721f.png)

## How to reproduce

1. Install KA Lite installer from http://dungeon.learningequality.org/browse/KL-MT16-145
1. After a successful installation, look at the footer like shown above.

**Comment by djallado** [comment]
The PATCH_VERSION = “3” `in version.py` If we download the source file via zip https://github.com/learningequality/ka-lite/archive/0.16.x.zip. 

But on  https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/version.py#L10
the PATCH_VERSION = “6"

In master branch if we download zip file, the PATCH_VERSION = “3” `in version.py`.

**Comment by benjaoming** [comment]
@djallado I can confirm that what you see is how things are.

This is because 0.16.6 was halted in the release process so the source on Github is actually the final source, however as we are waiting for data contents to be finalized we weren't able to release the final installers for OSX / PyPi / Windows / Debian.

I've opened up this issue to help lessen the confusion in the future:

https://github.com/learningequality/ka-lite/issues/5165
