### ISSUE TITLE
Include M2Crypto in OS-specific installers where possible

### ISSUE THREAD

**Issue by jamalex** [learningequality/installers#50]
We do a lot of crypto operations in KA Lite (and some, especially initial key generation, can be slow). KA Lite uses a bundled pure-Python library, [python-rsa](https://pypi.python.org/pypi/rsa), but will also take advantage of M2Crypto (which wraps openssl) if available, as it is _much_ faster.

We haven't been bundling M2Crypto because it includes C extensions, and hence need to be compiled in a platform-specific way. However, now that we're building platform-specific installers, it should be possible to bundle M2Crypto and have it installed somewhere to the path.

For Windows, it might be easiest to bundle the EXE installer as we do for Python, and install it during the installation process: http://chandlerproject.org/Projects/MeTooCrypto#Downloads

**Comment by benjaoming** [comment]
ka-lite-raspberry-pi already includes a dependency on python-m2crypto

I would be cautious about bundling compiled binary code, even in the installers.

AFAIK most use cases for the deb are about specific deployments that can handle dependencies in our .deb, but let's discuss this further.

The debian format includes the option of recommending packages, so I could start adding `Recommends: python-m2crypto` to the packages?

**Comment by benjaoming** [comment]
Because of the "maintenance mode" of KA Lite, it should be safe to assume that this "nice to have" improvement will not be done. It would affect the build process as it would require for compiled code to enter the installers. Should be safe to assume that won't be possible to prioritize, and probably won't be an acceptable change.

However, as stated, the main target for performance issues, Raspberry Pi, already has this dependency. And any other platform is free to install m2crypto from other sources as a performance boost.
