### ISSUE TITLE
Debian installer should have initconfig-like functionality

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#51]
That management command should really be the Debian installer's job, not a management command in KA Lite.

**Comment by benjaoming** [comment]
Thanks for opening this, was just about to do so :)

**Comment by benjaoming** [comment]
So I would suggest the following:

1. A custom user "kalite" is created by the debian installer with a default home in /var/kalite/ or something since it's not a normal user
1. A script for setting basic kalite ENV variables is put in /etc/default/kalite
1. /etc/init.d/ka-lite is installed and uses /etc/default/kalite and runs "kalite start" with this env -- we can't user /etc/init because Debian doesn't have Upstart by default.

**Comment by benjaoming** [comment]
I don't think ka-lite should run by default, so user has to run "update-rc.d ka-lite defaults" to add it as an automatically started service.

ka-lite-gtk should have buttons for adding/removing the start up job.

**Comment by benjaoming** [comment]
Okay the outlined solution should be this:

1. use `dh_installinit` in `debian/rules` to install an init.d script. Upstart is deferred for now, as it would mean fragmentation of documentation guides (`restart ka-lite` vs. `/etc/init.d/ka-lite restart`).
1. Use `adduser --system ka-lite` to add a system user with a home dir but no login. Will be added to `post` rules. User is NOT removed when uninstalling. https://wiki.debian.org/AccountHandlingInMaintainerScripts
1. Add /etc/default/ka-lite specifying the user that runs the `kalite` command and the command to run.

Please note that starting ka-lite is extremely slow, and it's very questionable to implement this as a default feature. On the contrary, the whole reason for having the feature seems to be that novice users should not have to bother with configuring an automatic start.

**Comment by jamalex** [comment]
I'm just trying to understand the implications here better. It sounds like you're proposing KA Lite be run in two different "modes", the per-user mode we're now enabling (to be used with for manual starts), and a "global" cross-user mode, running as a separate user with a shared user directory (for init.d startup).

- Especially now that user data (DB etc) is stored on a per-user basis, having the auto-started server run as a separate user sounds like it could lead to confusions, as it won't play well with the user then running `kalite start` etc (since that would run as a different user, and hence access a different DB etc).
- Rather than a cross-user service, perhaps this would be better to have this as a user-specific "Startup" application or crontab `@reboot` command (that calls `kalite start`), that will run after the user logs in. That way the user could still use `kalite stop` etc.

I agree that autostart shouldn't be enabled by default. We used to ask the user whether they wanted to autostart, during the setup process, and that worked well. Not sure where in the new system (pre-GTK) that could best happen, though.

**Comment by benjaoming** [comment]
Okay, pondering this a bit more:

I think we should go for the init.d solution and have it switched on by default because it aligns with my understanding of the most simple and general use case.

The intention of the /etc/default/ka-lite file is to have a place to specify the default user that runs **the** KA Lite server. As for the GTK interface, it will be designed so that users can specify who should run the server, this will affect the settings read by /etc/init.d/ka-lite

I think we need to grasp the most general use case and accommodate that. My guess, and please correct me if I'm wrong, is that someone installs ka lite, and then they expect it to work after that so they can play around with it. If they are going to use it, they just keep it and are happy that it auto-starts. They don't care which account it's running on. If they don't like it, they remove it again through the Software Center.

More advanced users could want to have control of starting and stopping the server through ka-lite-gtk. So they have the option of choosing which user account it's running under and to remove the init.d script from various runlevels.

Advanced users running ka-lite-gtk are aware that kalite runs as a specific user and stores data there, and running it as a different user will yield different results.

Even more advanced users will use the `kalite` command, and they can be assumed to be aware that there are different user accounts on a linux machine. We should maybe add special things for the kalite command to be aware *if* there is a ka-lite user account and to warn the user in these cases.

Creating a login-based daemon service is also possible, but you need to be sensible about exactly when the autostart should happen. Not in profile.d or bashrc or something for sure. There are XDG standards for this, but I'm not sure if the API has been stable over too many Ubuntu versions. But it could be a way of adding kalite as a service across many different desktop environments. I would tag this as a separate issue, though.. not really sure if it's a good way to go. Maybe for the ka-gtk-app once it has a system tray.

**Comment by benjaoming** [comment]
Okay things are starting to work...

```
➜  debian git:(debian-initial) ✗ sudo dpkg -i ka-lite_0.14.alpha3-0ubuntu1_all.deb
Selecting previously unselected package ka-lite.
(Reading database ... 236601 files and directories currently installed.)
Preparing to unpack ka-lite_0.14.alpha3-0ubuntu1_all.deb ...
Unpacking ka-lite (0.14.alpha3-0ubuntu1) ...
Setting up ka-lite (0.14.alpha3-0ubuntu1) ...

Configuration file '/etc/init.d/ka-lite'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** ka-lite (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/init.d/ka-lite ...
id: ka-lite: no such user
Adding system user `ka-lite' (UID 118) ...
Adding new user `ka-lite' (UID 118) with group `nogroup' ...
Creating home directory `/var/ka-lite' ...
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

Setting up KA Lite; this may take a few minutes; please wait!
                                  
  _   __  ___    _     _ _        
 | | / / / _ \  | |   (_) |       
 | |/ / / /_\ \ | |    _| |_ ___  
 |    \ |  _  | | |   | | __/ _ \ 
 | |\  \| | | | | |___| | ||  __/ 
 \_| \_/\_| |_/ \_____/_|\__\___| 
                                  
```

I left the part with the customized init.d script on purpose, it seems like it detects local changes to files, which is great :)

So what happens now:

1. User installs .deb or from PPA
1. A ka-lite user is added and a start up script
1. Start up script runs immediately and configures everything for the ka-lite user with home dir in /var/ka-lite
1. Final message output snippet:

```
...
You can now start KA Lite with the following command:

	kalite start


INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Copying static media...
WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.40.135:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/

Going to daemon mode, logging to /var/ka-lite/.kalite/server.log
Processing triggers for ureadahead (0.100.0-16) ...
```

**Comment by benjaoming** [comment]
Decisions to alleviate problems caused by user's confusion about who runs kalite:

1. Add a new warning in kalite if a ka-lite user exists and has data + user does not have any data.
1. debconf asking if kalite should start when booting (system service)
1. debconf to ask which user will run kalite system service if kalite system service is chosen

**Comment by MCGallaspy** [comment]
From our discussion earlier today, the desired behavior is this:
*  The init.d script runs ka-lite as a particular user (ka-lite by default, but should be configurable) which we'll call the ka-lite user
*  Anyone who starts the server using the init.d script (e.g. `sudo /etc/init.d kalite start`) will run the server as the ka-lite user.
*  A user can still run ka-lite at any privilege level (e.g. as themselves, if they are distinct from the ka-lite user), and this will create new user-data folders & files in that user's home directory.

@jamalex did I miss anything here?

**Comment by MCGallaspy** [comment]
Oops, I glazed over @benjaoming's comment above. But based on that I think our understanding is the same here. :)

**Comment by benjaoming** [comment]
![screenshot from 2015-07-07 02 21 36](https://cloud.githubusercontent.com/assets/374612/8536244/086943aa-244f-11e5-824a-a91fe6fe36e4.png)

**Comment by benjaoming** [comment]
I will fix the language error, but this is what happens at command-line level...

**Comment by benjaoming** [comment]
![screenshot from 2015-07-07 02 23 23](https://cloud.githubusercontent.com/assets/374612/8536264/2ce64692-244f-11e5-8f69-e123893abaef.png)

**Comment by benjaoming** [comment]
![screenshot from 2015-07-07 03 23 49](https://cloud.githubusercontent.com/assets/374612/8536886/9bbbb658-2457-11e5-93a9-762e1c7670dd.png)

![screenshot from 2015-07-07 03 23 49](https://cloud.githubusercontent.com/assets/374612/8536905/c62485be-2457-11e5-9e2c-0606d5fb70ce.png)

![screenshot from 2015-07-07 03 24 31](https://cloud.githubusercontent.com/assets/374612/8536906/ca676466-2457-11e5-8421-f0b9894a3673.png)
![screenshot from 2015-07-07 03 24 40](https://cloud.githubusercontent.com/assets/374612/8536908/cd8cfe62-2457-11e5-9da8-687e9fe3f2d5.png)
![screenshot from 2015-07-07 03 24 56](https://cloud.githubusercontent.com/assets/374612/8536909/cff4bb68-2457-11e5-9f97-6415363b7a5a.png)

**Comment by benjaoming** [comment]
Created the warning for non-default users running ka-lite: learningequality/ka-lite#4051

**Comment by benjaoming** [comment]
I don't see any point in keep things issue open... let's move on to having separate issues in case there's bugs or refinements.
