### ISSUE TITLE
Install pip dependencies when running ka-lite windows installer

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#53]
**Branch**: Master
**Target**: 0.14.x
**Expected behavior**: When running `ka-lite windows installer` it must automatically install the pip dependencies for ka-lite.
**Actual behavior**: Pip dependences is not automatically install when running `ka-lite windows installer` this issue is related to #48 .

**Comment by cpauya** [comment]
Adding the instructions from @aronasorman here:
...
[May-27 10:43 PM] Aron Fyodor Asor: yeah, so basically the windows installer isn't working now, since it doesn't grab the dependencies from pip
the way forward right now is to generate a static zip package with all dependencies by running 'python setup.py sdist --static'
that would create a zip file inside ka-lite/dist
now that is what will be included in the windows installer
and once installation on windows starts, you should do a 'pip install <zipfile>' to install.
...
