### ISSUE TITLE
No GUI interface for Debian install

### ISSUE THREAD

**Issue by rtibbles** [learningequality/installers#76]
Upon installing I am told:

"This package is run from the terminal, type: kalite"

**Comment by radinamatic** [comment]
I just installed through https://launchpad.net/~benjaoming/+archive/ubuntu/ka-lite, and you don't even get that... :D

**Comment by radinamatic** [comment]
I know that people who install on Linux are generally pretty knowledgeable, but I believe some indication of how to proceed should be included.

**Comment by benjaoming** [comment]
Currently, a prerequisite of fetching the .deb or adding the PPA is to read the docs :) The docs will soon say to run `kalite manage setup`, I'm adding that in a few minutes.

**Comment by radinamatic** [comment]
Sounds good enough! :)

**Comment by benjaoming** [comment]
The above message is still there because it's auto-generated by Software Center. However, it's leveraged by a couple of our own debconf messages.

During installation, users are informed of the init.d script and option of installing ka-lite-gtk

Until we start adding in ka-lite-gtk to the .deb itself, we have to live with this. Once we have a desktop shortcut included in the package, we can get rid of the Software Center message... so it'll be solved when ka-lite-gtk is okay'ed and bundled.
