### ISSUE TITLE
Installing alpha7 deb on Ubuntu - issues and recommendations

### ISSUE THREAD

**Issue by radinamatic** [learningequality/installers#86]
Ok, so I had alpha2 installed previously, used the link from https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite/+packages, deb file opened in Ubuntu Software Center:

![alpha7-1](https://cloud.githubusercontent.com/assets/1457929/8551441/df1b69b4-24d6-11e5-8411-f46ddecd16b0.png)

Maybe not urgent right now, but consider putting a pic/logo and shortening the title so it's not truncated in the Ubuntu Software Center window. I pressed the `Upgrade` button and the installation started. At certain point this Debconf window appeared:

![alpha7-4b](https://cloud.githubusercontent.com/assets/1457929/8551908/e5b8ba4e-24d9-11e5-9aa5-af51f22fd511.png)

Again, maybe not urgent, but consider putting a more human-redable window title, and `Yes` instead of `Forward` (to me at least sounds like a clearer message). Is `ka-lite` script and `/etc/init.d/` folder? The phrase might not be overly clear for non advance users... Next window:

![alpha7-5b](https://cloud.githubusercontent.com/assets/1457929/8552125/578463de-24db-11e5-9570-09d321d9b237.png)
 
Is `ka-lite` a new user you are proposing to create? It may be better to retrieve the users already available on the machine and offer the person who is installing to choose who will be the `owner`.

This is potentially important decision, so would it be possible to include this text directly inside the window itself, and not visible only by pressing the `Help` button? Second issue I'm not not clear about is: what is `by default`? User who will be the `owner`? I've changed the text in the field to my desktop user `didi`, pressed `Forward` and the following error appeared:

![alpha7-6b](https://cloud.githubusercontent.com/assets/1457929/8552518/e7851f12-24dd-11e5-9f96-12bd7651baf3.png)

```
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 309746 files and directories currently installed.)
Preparing to unpack .../ka-lite_0.14.alpha7-0ubuntu1_all.deb ...
Unpacking ka-lite (0.14.alpha7-0ubuntu1) over (0.14.alpha2-0ubuntu1) ...
Setting up ka-lite (0.14.alpha7-0ubuntu1) ...
Creating config file /etc/init.d/ka-lite with new version
insserv: script ka-lite: service kalite already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package ka-lite (--install): 
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing: ka-lite
```

Once I closed the window, it seemed that KA Lite was installed:

![alpha7-7](https://cloud.githubusercontent.com/assets/1457929/8551784/ecea73f8-24d8-11e5-9348-a593a1c55bf1.png)
 
At this point it is unclear what is user supposed to do, and how to start KA Lite, so maybe a message is warranted - it's not like in Windows system that you know it will be in the task bar. The only thing I could think of is to open Terminal and do the `kalite manage setup`. That part finished without any issues and I was able to start the server... :+1:

**Comment by benjaoming** [comment]
@radinamatic 
I'm afraid that most of the feedback, you need to send to Ubuntu because it's about how the debconf questions are presented. We can only adjust the raw text that you see, not window titles, buttons etc.

Neither can we put an icon in the software centre, because we distribute from a PPA or a raw .deb AFAIK.

As for the discussion on whether a new ka-lite user should be default: I think it's fine to do so, if people don't read the question or don't know their own username, we have different problems. But their remains a validation of the username entered, otherwise we create a new user account with e.g. a mis-spelled username.

Regarding your problem with the system service already existing: Remove any file you might already have called /etc/init.d/ka-lite before installing. It has nothing to do with the user account that you chose.

Good luck!

**Comment by benjaoming** [comment]
I will review the texts for the debconf items on next release. The part with /etc/init.d/ka-lite is not supposed to be confusing but is an important information for users who have a bit of command line experience (not using upstart or systemd though because they are not guaranteed on the host system).

**Comment by radinamatic** [comment]
@benjaoming 
I understand that ATM you/we have no way to "adapt" the **debconf** window since it depends on Ubuntu, or add the icon on USC because of the way we distribute the installer.

The discussion boils down to how 'expert' we expect our users to be (maybe the research @jamalex was doing can shed some light on that). Even if somebody is technically KA Lite Admin (the one who will install the server, language packs, etc...) they may not necessarily have "command line experience". Heck, I don't have a lot of "command line experience", and even though I have installed and uninstalled a fair amount of programs on Ubuntu over the years, this is the first time I've seen the **debconf** window. 

I believe that in general we can save ourselves a lot of future headaches and support issues/questions if we assume our users to be less than more knowledgeable, and expect/need much more Help, Documentation, and clear instructions. From the example installation above:

- I don't recall creating config file `/etc/init.d/ka-lite` on previous installations, so that must have been done during the installation without my previous explicit knowledge and approval (not saying it shouldn't have, just that I wasn't aware of it). If that can cause problems and/or errors with every subsequent installation (as experienced above), than the user should be warned in advance, and offered a solution in case the error does appear.

- The only reason I knew to do `kalite manage setup` after the installation finished, is because I'm here on GH, I have access to HipChat and the BugBach doc. How is a "normal" user supposed to know what to do at that point? Windows installer offers more to the user in that sense, and I don't believe we should assume that every Linux user is automatically more experienced (or foresighted) than the Windows one.         

Not trying to pick your installer apart here, overall it works great, I'm just trying to put myself in the shoes of the potential admin who has, more or less, my level of "expertise", and prevent problems they might encounter when trying to install KA Lite... :)

**Comment by jamalex** [comment]
> I don't recall creating config file /etc/init.d/ka-lite on previous installations, so that must have been done during the installation without my previous explicit knowledge and approval (not saying it shouldn't have, just that I wasn't aware of it). If that can cause problems and/or errors with every subsequent installation (as experienced above), than the user should be warned in advance, and offered a solution in case the error does appear.

+1 on this -- since it's unlikely that /etc/init.d/ka-lite belongs to any other user, it should be safe to overwrite. In fact, we should probably delete the file (as part of cleaning up old installations) if it does exist, since otherwise they may get the old git-based version of KA Lite auto-starting instead, which is bad.

> The only reason I knew to do kalite manage setup after the installation finished, is because I'm here on GH, I have access to HipChat and the BugBach doc. How is a "normal" user supposed to know what to do at that point? Windows installer offers more to the user in that sense, and I don't believe we should assume that every Linux user is automatically more experienced (or foresighted) than the Windows one.

It should have been OK with a fresh install to just start the server with `kalite start`, and it would detect that the DB wasn't initialized, and run setup as part of the initial startup process. For later upgrades, however, when there's an existing DB, we'll need to ensure that `setup` gets run, since it doesn't currently detect that `setup` is needed unless the DB is totally uninitialized.

The point about knowing what to do when the installer is finished is an excellent one.
- Part of this can be from the documentation. However, while the pip installation instructions show what to do after installing, the Deb instructions currently do not: http://field.learningequality.org/develop/docs/installguide/install_all.html#linux-debian-ubuntu-installation
- Even better would be to tell the user what to do at the end of the Deb installation process, with a popup window (if it's a fresh install, at least -- wouldn't want this for unattended upgrades). E.g. a popup with the message `Installation is complete! Open a terminal and enter "kalite start" to start KA Lite, or "kalite help" to see other options.`

**Comment by jamalex** [comment]
We also may need to remove the "add autostart" stuff from the `setup` management command.

**Comment by benjaoming** [comment]
@radinamatic 
Reviewing your error again, it's not actually because the file is there, it's because a service is recognized as installed with the same name. It's a bit odd.

Anyways, here are two good commands to ensure that previous configuration files are deleted before installing:

    apt-get purge ka-lite  # Removes ka-lite
    apt-get --purge autoremove  # Purges any other packages that can be automatically removed

I managed to get into problems, too, about alternating between my ka-lite and ka-lite-raspberry-pi debs and found the above to be useful for forcing /etc/init.d/ka-lite to be removed prior to user modifications of the system.

@jamalex dpkg manages md5 checksums of all the installed files and configuration files in order to avoid overwriting user modified configuration files.

**Comment by benjaoming** [comment]
...avoiding to overwrite these files is a feature because it avoids breaking peoples systems when updating.

**Comment by radinamatic** [comment]
@benjaoming Thank you for the commands, I'll try them out! :)

My main & only point here was that we shouldn't leave the user wondering what a possible error means, and which command might get them out of it. In that sense I give a big :+1: to BOTH suggestions by  @jamalex: update the deb docs, and add the popup/alert message for the user to continue configuring KA Lite inside the terminal.

**Comment by benjaoming** [comment]
There's been a lot of efforts going in to this .deb, so I would welcome the process of documenting and adding user guiding messages after we've settled that the technical aspects work. It takes a lot of time to change tings and test them.

As said earlier, I'll be reviewing the texts for debconf. One of the options here is to display a final text message about command line usage.

**Comment by benjaoming** [comment]
@jamalex 
>  We also may need to remove the "add autostart" stuff from the setup management command.

Sorry, I might have missed this comment.

I've opened #4222 for removing some of the "noise" made by alternative installation scripts that we should no longer support.. #3736 was merged to add a deprecationwarning for `kalite manage initdconfig`.

`kalite manage setup` doesn't call initdconfig and doesn't add any autostart stuff, so I think it's safe to remove.

**Comment by benjaoming** [comment]
@radinamatic 

I've found a way to set the window title:

![better_configuration_window](https://cloud.githubusercontent.com/assets/374612/9175377/aa5eadfc-3f85-11e5-8648-dd97e873fd0e.png)

**Comment by radinamatic** [comment]
Way to go, maestro! :bow:
 :+1: :+1: :+1:

**Comment by benjaoming** [comment]
Okay, I've opened #128 for one of your remaining comments, but closing this one.

Please open up separate issues if there are more suggestions and thanks for the work!!
